version: 0.2

phases:
  install: 
    commands:
      - cargo fetch
  build:
    commands:
      - cargo build --bins --tests
      - cargo test
  post_build:
    commands:
      - echo Build completed on `date`
