[package]
name = "football-puzzle"
version = "0.1.0"
authors = ["Gordon Govan <gordon@ggovan.uk>"]
edition = "2018"

[dependencies]
aoc-common = { path = "../aoc-common" }


# itertools = "0.9.0"
# lazy_static = "1.4.0"
# regex = "1.4.2"
tokio = { version = "1", features = ["full"] }