[package]
name = "aoc-2019"
version = "0.1.0"
authors = ["Gordon Govan <gordon@ggovan.uk>"]
edition = "2018"

[dependencies]
aoc-common = { path = "../aoc-common" }

itertools = "0.9.0"
text_io = "0.1.8"